DECLARE @vTableName sysname = 'Base01'

;WITH CTE AS
(
	SELECT	UPPER(TABLE_NAME) AS TABLE_NAME, 
			STRING_AGG(UPPER(COLUMN_NAME),', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) AS COL_LIST,
			STRING_AGG(''''+CASE 
								WHEN DATA_TYPE LIKE '%char' THEN dbo.GetRandomString(CHARACTER_MAXIMUM_LENGTH,0) 
								ELSE CONVERT(VARCHAR,CEILING(RAND()*10))
							END+'''',', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) AS COL_VALUE
	FROM	INFORMATION_SCHEMA.COLUMNS
	WHERE	COLUMN_NAME  NOT IN ('ID','CREATE_DATE','UPDATE_DATE')
		AND TABLE_NAME = @vTableName
	GROUP BY TABLE_NAME
)
SELECT  'INSERT INTO '+TABLE_NAME+' ('+COL_LIST+') VALUES('+COL_VALUE+')'
FROM CTE
UNION ALL
SELECT  'INSERT INTO '+TABLE_NAME+' ('+COL_LIST+') VALUES('+COL_VALUE+')'
FROM CTE
UNION ALL
SELECT  'INSERT INTO '+TABLE_NAME+' ('+COL_LIST+') VALUES('+COL_VALUE+')'
FROM CTE
UNION ALL
SELECT  'INSERT INTO '+TABLE_NAME+' ('+COL_LIST+') VALUES('+COL_VALUE+')'
FROM CTE
UNION ALL
SELECT  'INSERT INTO '+TABLE_NAME+' ('+COL_LIST+') VALUES('+COL_VALUE+')'
FROM CTE
UNION ALL
SELECT  'INSERT INTO '+TABLE_NAME+' ('+COL_LIST+') VALUES('+COL_VALUE+')'
FROM CTE